### ISSUE TITLE
erro instalação no raspberry

### ISSUE THREAD

**Issue by jeffersonkr** [Laiser/pynbiobsp#1]
qual SO e a versão utilizada para instalacao do driver no raspberry?

Agradeço desde ja.

**Comment by Laiser** [comment]
Ubuntu Mate 16.04 para ARM.

**Comment by jeffersonkr** [comment]
Obrigado!! consegui instalar o driver com sucesso no ubuntu mate arm, mas quando tento rodar o arquivo de test_fingerprint.py ele aparece erro: "cannot access '/dev/ngstar[0-9]*' : No such file or directory"
ERROR Unable to connect to device..
Desconectei o usb do hardware e reconectei mas mesmo assim nao aparece o ngstar no /dev/
Sabe qual o problema?

**Comment by Laiser** [comment]
Qual o modelo do leitor que tu tá usando?

**Comment by jeffersonkr** [comment]
HAMSTER HFDU06
creio que seja o DX

**Comment by Laiser** [comment]
Pode ser o Driver o leitor que eu testei foi Hamster III - Nitgen - HFDU06S

**Comment by jeffersonkr** [comment]
sabe aonde consigo o driver desse modelo ? HAMSTER HFDU06?

**Comment by jeffersonkr** [comment]
adquiri o modelo hfdu06s e consegui instalar no raspbian com kernel 4.4 depois de muitas tentativas.
agora estou com duvida se há alguma forma dele fazer uma verificação se há algum dedo no modulo sem fazer o capture

**Comment by Laiser** [comment]
Eu também gostaria de saber, eu sei que para windows tem uma DLL que tem a função de verificar se tem um dedo no leitor, mas para linux parece que não tem.
